export enum Role {
  ADMIN = 'ADMIN',
  AGRONOMIST = 'AGRONOMIST',
  DRONE_OPERATOR = 'DRONE_OPERATOR',
  TECHNICIAN = 'TECHNICIAN',
  MANAGER = 'MANAGER',
  VIEWER = 'VIEWER',
}

export enum GrowthStatus {
  PLANTED = 'PLANTED',
  GROWING = 'GROWING',
  HARVEST_READY = 'HARVEST_READY',
  HARVESTED = 'HARVESTED',
}

export enum HealthStatus {
  HEALTHY = 'HEALTHY',
  MODERATE_STRESS = 'MODERATE_STRESS',
  SEVERE_STRESS = 'SEVERE_STRESS',
  UNKNOWN = 'UNKNOWN',
}

export enum NotificationType {
  WEATHER_ALERT = 'WEATHER_ALERT',
  IOT_ANOMALY = 'IOT_ANOMALY',
  HARVEST_READY = 'HARVEST_READY',
  HEALTH_DEGRADATION = 'HEALTH_DEGRADATION',
  SYSTEM_INFO = 'SYSTEM_INFO',
}

export enum NotificationPriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}
